import type { NextPage } from 'next';
import Head from 'next/head';

import Navbar from 'components/layout/Navbar';
import Homepage from 'features/homepage';
import Footer from 'components/layout/Footer';
/**
 * - Setup ESLint and Prettier
 * - Implement Navbar
 * - Setup Document.js
 * - Setup Head tag
 * - Add Navbar and Footer in Head component as wrapper
 * - Implement Hero section
 * - Import svg, png
 */
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hans Tanawi | Frontend Engineer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-white font-basic'>
        <Navbar />
        <Homepage />
        {/* <Footer /> */}
      </div>
    </>
  );
};

export default Home;
